### ISSUE TITLE
Items and search endpoints are not ItemCollections

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cmr-stac#10]
The /collections/{collectionId}/items and /stac/search endpoints should return an ItemCollection, as per:
https://github.com/radiantearth/stac-spec/blob/v0.8.1/api-spec/api-spec.md#ogc-api---features-endpoints

ItemCollection definition:
https://github.com/radiantearth/stac-spec/blob/v0.8.1/item-spec/itemcollection-spec.md

Basically the `type` and `links` fields are missing to make it a valid GeoJSON FeatureCollection.

Also note that OGC API - Features requires some additional fields as well, such as `numMatched` and `numReturned`.

**Comment by RincioneCMR** [comment]
Verified.
