### ISSUE TITLE
STAC-API compatibility / use with search libraries

### ISSUE THREAD

**Issue by scottyhq** [nasa/cmr-stac#101]
I'd love to use this endpoint with the Python sat-search client library, but am running into issues that I believe are due to incompatibilities with the STAC API specification (https://github.com/radiantearth/stac-api-spec).

Cross-referencing issue in the sat-search repo: https://github.com/sat-utils/sat-search/issues/106#issuecomment-728595571

cc @matthewhanson

**Comment by matthewhanson** [comment]
I closed the issue in sat-search, although they were really all issues with CMR-STAC, and I think all have now been resolved.

Note that [pystac-client](https://github.com/stac-utils/pystac-client) is the preferred software client and replaces sat-search

Thanks @scottyhq !
