### ISSUE TITLE
Fields missing from individual Item

### ISSUE THREAD

**Issue by DrewE84** [nasa/cmr-stac#104]
I noticed a bit of a discrepancy between what information is given when looking at a list of items versus what's displayed when looking at a singular item. Particularly, the `stac_extensions` and `eo:cloud_cover` fields. 

Again, this information is displayed when looking at the `.../<collectionID>/items`, but not when I click on a specific Item's `self` link `.../<collectionID>/items/<itemID>`. Below I've put two links as an example.

Displayed: https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/C1711924822-LPCLOUD/items
Not Displayed: https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/C1711924822-LPCLOUD/items/G1969487860-LPCLOUD

**Comment by matthewhanson** [comment]
Thanks for this @DrewE84 
This has been fixed in development and should be deployed to production in the coming weeks.
