### ISSUE TITLE
Missing required fields from Collections: stac_version, license

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cmr-stac#13]
`stac_version` and `license` fields are required for collections, but missing from cmr-stac

Also, it is encouraged to populate providers, which is not being surfaced in cmr-stac, but the relevant data does exist in the UMM.

as per
https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#collection-fields

**Comment by RincioneCMR** [comment]
Verified.
