### ISSUE TITLE
Document release cadence

### ISSUE THREAD

**Issue by scottyhq** [nasa/cmr-stac#130]
@matthewhanson  if I understand correctly, the `master` branch of this repository is not continuously deployed. It would be helpful to know when releases are being made or perhaps add a deployment version tag to the landing page metadata (https://cmr.earthdata.nasa.gov/stac)

I think this would help sort out when libraries using the proxy start manifesting errors, for example https://github.com/sat-utils/sat-search/issues/106

**Comment by matthewhanson** [comment]
Hi @scottyhq you are correct that the master branch is not deployed automatically.
What happens is the master branch is deployed nightly internally to a testing environment. On a 2 week schedule it is deployed to UAT (https://cmr.uat.earthdata.nasa.gov/stac), which is publicly available but has a completely different set of data in it (some of it test data, it's not useful to users). On the same 2 week schedule validated changes on UAT get deployed to PROD which is what you are using.

I agree this process should be more transparent, especially with some upcoming changes. For instance, the collection IDs will be changing on PROD within the month to something more human readable.  For instance, `C1379757686-USGS_EROS` new ID will be `EO1_ALI.v1` (https://cmr.earthdata.nasa.gov/search/collections.json?concept_id=C1379757686-USGS_EROS)

The releases are tagged with versions in this repo, but there's no info on what versions are deployed when and where.

**Comment by sharkinsspatial** [comment]
@matthewhanson It doesn't look like there are any release tags in the repo.  I was a just trying to trace a broken response to a release and couldn't find any tags.  But it was a nice error as it was caused by your great fixes here https://github.com/nasa/cmr-stac/pull/129  :]

**Comment by matthewhanson** [comment]
@sharkinsspatial Ah sorry they are branches, not tags. At any given time production is most likely at the 2nd highest version number, maybe 3rd.  #129 isn't on production, or at least it shouldn't be yet. Are you running cmr-stac locally?

**Comment by aliciaaleman** [comment]
Release notes are now being posted to this repo two weeks ahead of production releases: https://github.com/nasa/cmr-stac/releases

The release cadence is every two weeks.
