### ISSUE TITLE
pagination for collections should use rel=next instead rel=child

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cmr-stac#14]
There is pagination of sorts the listing of provider collections:
https://cmr-stac-api.dev.element84.com/stac/catalog/providers/LAADS

The last link is:
```
{
rel: "child",
title: "Page 2",
href: "https://cmr-stac-api.dev.element84.com/stac/catalog/providers/LAADS/page/2"
}
```

Neither STAC nor OGC API Features define pagination for collection endpoints, but the same approach should be used as for items, which is to use a `rel=next` link, rather than child

**Comment by RincioneCMR** [comment]
![image](https://user-images.githubusercontent.com/43647907/81582064-96e4e600-937d-11ea-8def-86be875def8d.png)

Pagination seems to be using rel=next, does this satisfy the acceptance criteria for this issue?

**Comment by RincioneCMR** [comment]
Verified with Matt Hanson.
