### ISSUE TITLE
bbox should accept an array

### ISSUE THREAD

**Issue by scottyhq** [nasa/cmr-stac#149]
the endpoint should accept bbox passed as an array instead of a string of comma separated floats. cc @matthewhanson 

Mirroring an issue documented in https://github.com/sat-utils/sat-search/issues/106#issuecomment-796348470 

```python
results = Search(url='https://cmr.earthdata.nasa.gov/stac/LPCLOUD',
                 collections=['HLSS30.v1.5'], 
                 #bbox = [-122.4,41.3,-122.1,41.5], #SatSearchError: "Request failed with status code 400"
                 bbox = '-122.4,41.3,-122.1,41.5', #works! 
                 datetime='2021-01-01/2021-02-01',  
                )
results.found()
```

**Comment by matthewhanson** [comment]
@scottyhq I've already got this filed as an issue and was going to be fixing it this week, but there's a complicating factor with the deployment that's preventing mutlivalue parameters from getting passed on. So, if I fix it now it will work for POST but will break GET. Hope to have a resolution soon.

**Comment by RichardScottOZ** [comment]
Thanks Matthew.

**Comment by matthewhanson** [comment]
This is scheduled for deployment to production June 8
