### ISSUE TITLE
Invalid path components

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cmr-stac#16]
cmr-stac allows one to browse through some top level catalogs before getting to collections, which is fine, but the path components do not follow the STAC spec, so the existing clients are unable to work with it.

The provider:
https://cmr-stac-api.dev.element84.com/stac/catalog/providers/ASF

seems like it should essentially be a root catalog, and the STAC endpoints should go from here, which would be useful and allow for cross-collection searches from a single provider, but:
https://cmr-stac-api.dev.element84.com/stac/catalog/providers/ASF/stac
https://cmr-stac-api.dev.element84.com/stac/catalog/providers/ASF/stac/search
etc. do not work

Instead a collection goes back a level to something like:
https://cmr-stac-api.dev.element84.com/stac/catalog/collections/C1213928843-ASF

This implies that the root is
https://cmr-stac-api.dev.element84.com/stac/catalog
which is invalid, and that:
https://cmr-stac-api.dev.element84.com/stac/catalog/stac
would be the root catalog, which is also invalid

**Comment by tvance34** [comment]
/search only accepts certain parameters (collections, limit, intersects, datetime, bbox, ids).  anything else will return an error stating invalid search parameter.

**Comment by RincioneCMR** [comment]
Verified.
