### ISSUE TITLE
Invalid stac-api-spec conformance reporting.

### ISSUE THREAD

**Issue by sharkinsspatial** [nasa/cmr-stac#166]
The reported conformance for `item-search#fields`, `item-search#query` and `item-search#sort` are currently non-functional but reported in the conformance at `` ` `` curl --location --request GET ' [https://cmr.earthdata.nasa.gov/stac/LPCLOUD'](https://cmr.earthdata.nasa.gov/stac/LPCLOUD') `` ` `` See `` ` `` curl --location --request GET ' [https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSL30.v1.5/items?fields=-geometry'](https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSL30.v1.5/items?fields=-geometry') `` ` `` and `` ` `` curl --location --request GET ' [https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSL30.v1.5/items?sortby=+properties.datetime'](https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSL30.v1.5/items?sortby=+properties.datetime') `` ` `` as failing examples.

**Comment by william-valencia** [comment]
These are working now
https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSL30_2.0/items?fields=-geometry
https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSL30_2.0/items?sortby=+properties.datetime
