### ISSUE TITLE
POST /search with bbox fails with 400 with only a formatting change.

### ISSUE THREAD

**Issue by philvarner** [nasa/cmr-stac#170]
This query with a `bbox` parameter fails with a 400:

```
curl -X "POST" "https://cmr.earthdata.nasa.gov/stac/LARC_ASDC/search" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{ "bbox": [ 0, 0, 1, 1 ] }'
```

But this one, *which should be identical* does not:

```
curl -X "POST" "https://cmr.earthdata.nasa.gov/stac/LARC_ASDC/search"      -H 'Content-Type: text/plain; charset=utf-8'      -d $'{
  "bbox": [
0,
0,
1,
1
  ]
}'
```

This isn't specific to curl, as I'm getting this same error using the Paw http client.

**Comment by matthewhanson** [comment]
Thanks, odd, but I'll test this locally and see how it's parsing that.

**Comment by philvarner** [comment]
Any update?

**Comment by matthewhanson** [comment]
Is this still valid?  I'm not sure if this is a CMR-STAC issue, or just the way that curl sends that argument to CMR-STAC, or if it's a problem with the LARC_ASDC data which has been confirmed to be causing some serious latency issues.

**Comment by philvarner** [comment]
I tried it with USGS_EROS and it works, so latency would be a good explanation. I'm going to close this issue b/c I just realized my second query above that works is only working because the content-type is set to text/plain -- my mistake!

**Comment by matthewhanson** [comment]
Great thanks for all your testing @philvarner !
