### ISSUE TITLE
Use API Gateway. in place of Application Load Balancer in serverless deployment

### ISSUE THREAD

**Issue by abarciauskas-bgse** [nasa/cmr-stac#174]
According to @matthewhanson we should be able to use API Gateway in place of the application load balancer, this ticket is to replace the following lines:

https://github.com/nasa/cmr-stac/blob/master/search/serverless.yml#L35-L39

with an API Gateway

**Comment by matthewhanson** [comment]
This has been fixed in master with the addition of a plain serverless.yml file that should be used for deployment. The previous serverless.yml was specific to NASA's deployment environment and has been renamed to `serverless-ngap.yml`
