### ISSUE TITLE
Item Search datetime query parameter with only date is allowed, but should not

### ISSUE THREAD

**Issue by philvarner** [nasa/cmr-stac#183]
date-only datetime strings are not allowed for the `datetime` query parameter per OAFeat and STAC API Item Search.

However, cmr-stac allows these when it should not. E.g. `https://cmr.earthdata.nasa.gov/stac/LARC_ASDC?datetime=1985-04-12` does not return a 400 status code and instead implements the semantics of `../1985-04-12T00:00:00Z`. This is also a confusing behavior, as `https://cmr.earthdata.nasa.gov/stac/LARC_ASDC?datetime=../1985-04-12` returns no results and `https://cmr.earthdata.nasa.gov/stac/LARC_ASDC?datetime=1985-04-12/..` returns a 400.

**Comment by demiurg** [comment]
This is still true, and still relevant.

**Comment by william-valencia** [comment]
Search is returning 400 for these now:

https://cmr.earthdata.nasa.gov/stac/LARC_ASDC/search?datetime=1985-04-12
