### ISSUE TITLE
Some collections are completely invalid

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cmr-stac#19]
Some collections that are surfaced are completely invalid, missing most required fields except 'description' and 'links'. They even are missing 'id' and instead have 'name' which is not a STAC field.

This seems to be most of thecollections from the LAADS provider:
https://cmr-stac-api.dev.element84.com/stac/catalog/providers/LAADS

Example:
https://cmr-stac-api.dev.element84.com/stac/catalog/collections/C1443541366-LAADS

**Comment by matthewhanson** [comment]
Actually, when browsing through the providers here:
https://cmr-stac-api.dev.element84.com/stac/catalog/providers

It seems like all the collections are like that.   It's not clear what the intended behavior is.

**Comment by matthewhanson** [comment]
And found a collection which does have the extent field, but no `id` field, just `name`:
https://cmr-stac-api.dev.element84.com/collections/C1213921661-ASF

**Comment by RincioneCMR** [comment]
Verified, going to close the ticket.  The specific examples listed here are now working properly, and every collection we've tested passes validation.  If we see issues with junk or missing metadata, we can file a follow-on issue.
