### ISSUE TITLE
LPCLOUD Status Code 400

### ISSUE THREAD

**Issue by RichardScottOZ** [nasa/cmr-stac#191]
![image](https://user-images.githubusercontent.com/72196131/126952747-c318f980-799b-4d4f-a5bb-407324ea3acd.png)

Same as #153 - tried the same example in there.

**Comment by william-valencia** [comment]
Was able to run this with a limit of 200.
<img width="1270" alt="Screenshot 2024-10-15 at 1 34 07 AM" src="https://github.com/user-attachments/assets/a0032838-9ca9-44ae-bb2d-7a947ff71551">
