### ISSUE TITLE
"next" links use URL escaping that the server doesn't understand

### ISSUE THREAD

**Issue by Kodiologist** [nasa/cmr-stac#205]
Consider for example [https://cmr.earthdata.nasa.gov/stac/LPDAAC_ECS/search?bbox=-76,42,-75,43&amp;collections=MOD21A1D.v061&amp;limit=1](https://cmr.earthdata.nasa.gov/stac/LPDAAC_ECS/search?bbox=-76,42,-75,43&collections=MOD21A1D.v061&limit=1) . The "next" link here is [https://cmr.earthdata.nasa.gov/stac/LPDAAC_ECS/search?bbox=-76%2C42%2C-75%2C43&amp;collections=MOD21A1D.v061&amp;limit=1&amp;page=2](https://cmr.earthdata.nasa.gov/stac/LPDAAC_ECS/search?bbox=-76%2C42%2C-75%2C43&collections=MOD21A1D.v061&limit=1&page=2) , which returns HTTP 400. If you unescape the commas, yielding [https://cmr.earthdata.nasa.gov/stac/LPDAAC_ECS/search?bbox=-76,42,-75,43&amp;collections=MOD21A1D.v061&amp;limit=1&amp;page=2](https://cmr.earthdata.nasa.gov/stac/LPDAAC_ECS/search?bbox=-76,42,-75,43&collections=MOD21A1D.v061&limit=1&page=2) , it works.

**Comment by demiurg** [comment]
https://www.rfc-editor.org/rfc/rfc3986#section-2.2

Commas seem to be in a set of characters that should be percent encoded in GET values. So, the GET values should be percent decoded before interpreted further.

**Comment by william-valencia** [comment]
Next links are properly escaped now. See
https://cmr.earthdata.nasa.gov/stac/LPDAAC_ECS/search?bbox=-74.5,40.2128,-73.5,41.2128&collections=AST_L1T_003&limit=1

...
{
      "rel": "next",
      "href": "https://cmr.earthdata.nasa.gov/stac/LPDAAC_ECS/search?bbox=-74.5%2C40.2128%2C-73.5%2C41.2128&collections=AST_L1T_003&limit=1&cursor=eyJqc29uIjoiW1wibHBkYWFjX2Vjc1wiLDk1NDY5MTk2NDI5NiwxMDEyMzA4Njg2XSIsInVtbSI6IltcImxwZGFhY19lY3NcIiw5NTQ2OTE5NjQyOTYsMTAxMjMwODY4Nl0ifQ%3D%3D",
      "type": "application/geo+json",
      "title": "Next page of results"
 }
...
