### ISSUE TITLE
stac-api-spec query extension no longer functions.

### ISSUE THREAD

**Issue by sharkinsspatial** [nasa/cmr-stac#206]
The test [spec](https://github.com/nasa/cmr-stac/blob/6e403cb35a3d4c3c746bd134b577795157d384af/search/tests/api/extensions/query.spec.js) appears to indicate that the use of the stac-api-spec [query extension](https://github.com/radiantearth/stac-api-spec/blob/master/item-search/README.md#query-extension) is supported but while the following query functions.

This search result in 1304 matched items `` ` `` curl --location --request POST ' [https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search'](https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search') \ --header 'Content-Type: application/json' \ --data-raw '{ "datetime": "2021-01-28", "collections": ["HLSL30.v2.0"] }' `` ` ``

But including a `query` object (which should not affect the number of matched items) results in 0 items being returned `` ` `` curl --location --request POST ' [https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search'](https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search') \ --header 'Content-Type: application/json' \ --data-raw '{ "datetime": "2021-01-28", "collections": ["HLSL30.v2.0"], "query": { "eo:cloud_cover": { "gte": 0, "lte": 100 }} }' `` ` ``

**Comment by william-valencia** [comment]
Just tried this with a datetime range:
curl --location --request POST 'https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search'  --header 'Content-Type: application/json'  --data '{ "datetime": "2021-01-28T00:00:00.00Z/2021-01-29T00:00:00.00Z", "collections":["HLSL30_2.0"] }'

and

curl --location --request POST 'https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search'  --header 'Content-Type: application/json'  --data '{ "datetime": "2021-01-28T00:00:00.00Z/2021-01-29T00:00:00.00Z", "collections":["HLSL30_2.0"], "query": { "eo:cloud_cover": { "gte": 0, "lte": 100 }} } '

And they both return 1304 matched items.
