### ISSUE TITLE
502 Bad Gateway error when querying stac/ASF

### ISSUE THREAD

**Issue by kvenkman** [nasa/cmr-stac#213]
This code snippet `` ` `` from pystac_client import Client catalog_asf = Client.open(' [https://cmr.earthdata.nasa.gov/stac/ASF'](https://cmr.earthdata.nasa.gov/stac/ASF')) products = [c for c in catalog_asf.get_children()] `` ` `` results in an error, ending with `` ` `` APIError: 502 Bad Gateway

# 502 Bad Gateway

]() `` ` `` However, this works fine: `` ` `` from pystac_client import Client catalog_asf = Client.open(' [https://cmr.earthdata.nasa.gov/stac/ASF'](https://cmr.earthdata.nasa.gov/stac/ASF')) products = [c for c in catalog_asf.get_collections()] products = [c for c in catalog_asf.get_children()] `` ` ``

I.e., a call to `get_collections()` followed by a call to `get_children()`. However, the first method returns a complete list of data products available at ASF, while the latter only returns a subset.

**Comment by jaybarra** [comment]
Duplicates #192

**Comment by william-valencia** [comment]
Just tried this today. Although it took a while to go through all the data, I was able to get through with no 502 errors.

<img width="1346" alt="Screenshot 2024-10-14 at 1 07 31 AM" src="https://github.com/user-attachments/assets/4b81e285-295b-4f3c-99ad-3ed889f79b1e">
