### ISSUE TITLE
search takes invalid parameters

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cmr-stac#23]
I found out the proper way to search a collection by using the search link from the collection...except it is using a parameter called `collectionId` which is not a valid parameter

https://pcmii5dog3.execute-api.us-east-1.amazonaws.com/dev/stac/search?collectionId=C1443528505-LAADS

collections are searched via a `collections` parameter, and a list may be provided.

I think the confusion came from the fact that 'collectionId' is given in this table:
https://github.com/radiantearth/stac-spec/blob/master/api-spec/api-spec.md#filter-parameters-and-fields

But it is a *path-only* parameter, meaning that it is used to specify the collection in an items endpoint like:
https://pcmii5dog3.execute-api.us-east-1.amazonaws.com/dev//collections/C1631076765-NSIDC_ECS/items

where C1631076765-NSIDC_ECS is the collectionId

**Comment by RincioneCMR** [comment]
Duplicate to #16, verified.
