### ISSUE TITLE
wrong ordering of spatial extent in collections

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cmr-stac#25]
the spatial extent in collections is the same as a GeoJSON bounding box, so [minlon, minlat, maxlon, maxlat], but lat and lon are backwards in the cmr-stac collections.

Example:
https://pcmii5dog3.execute-api.us-east-1.amazonaws.com/dev//collections/C1426717545-LANCEMODIS

**Comment by RincioneCMR** [comment]
Verified.
