### ISSUE TITLE
Number of `Item`s within `Catalog` response capped at 1000?

### ISSUE THREAD

**Issue by kylebarron** [nasa/cmr-stac#278]
If I fetch an HLS STAC `Catalog` such as:
```
https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSS30.v2.0/2022/07/01
```
or 
```
https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSL30.v2.0/2020/07/07
```
the total number of entries in the `links` list is 1003 with only 1000 links of type `rel: item`. 

If I fetch and visualize all those child `Item`s, they're only in one geographic region:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/15164633/222239670-2160bac8-d400-409d-8930-35654a370579.png">

This behavior is quite consistent across various dates. Here are the first 4 days of HLSS30 above:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/15164633/222240006-ee4316fd-86cd-47f6-9da5-f26308c86d06.png">

This leads me to believe that the `Catalog`s are limited to only 1000 child `Item`s. How can I access more than this limit?

**Comment by william-valencia** [comment]
When accessing items if your chosen collection ie: https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSS30_2.0/items
There will be a "next" link in the links field near the bottom:

"links": [
    {
      "rel": "self",
      "href": "https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSS30_2.0/items",
      "type": "application/geo+json"
    },
    ...
    {
      "rel": "next",
      "href": "https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSS30_2.0/items?cursor=eyJqc29uIjoiW1wibHBjbG91ZFwiLDE0NDg2Njk4NDc0NTAsMjcxMTQ3NzY3OF0iLCJ1bW0iOiJbXCJscGNsb3VkXCIsMTQ0ODY2OTg0NzQ1MCwyNzExNDc3Njc4XSJ9",
      "type": "application/geo+json"
    }

You can use this link/href to access the next set of results.
