### ISSUE TITLE
original metadata should be an asset, not a link

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cmr-stac#29]
See this example:
https://pcmii5dog3.execute-api.us-east-1.amazonaws.com/dev//collections/C1443528505-LAADS/items/G1465827297-LAADS

there is a link that is "metadata".  Metadata should be an asset, not a link.

Links are primarily for including the hierarchical links (self, parent, child, root, collection), but may also be external related links such as: related software, scientific papers, license info, etc.
If it is the data itself or associated metadata for the data, it should be an asset.

**Comment by RincioneCMR** [comment]
Verified.
