### ISSUE TITLE
missing assets in ECO_L2T_LSTE.v002 cmr stac

### ISSUE THREAD

**Issue by Berhinj** [nasa/cmr-stac#314]
Please guide me if this should be posted somewhere else.

I notice that when searching on cmr search (via earth data search), I'm getting a "view_zenith.tif" which I don't have as assets for in the cmr stac catalog.

It should be fixed right? Can someone help me with this?

```
import numpy as np
import pystac_client
import rioxarray as rxr  # noqa: F401

href = "https://cmr.earthdata.nasa.gov/stac/LPCLOUD"
c = pystac_client.Client.open(href)

params = dict(
    collections=["ECO_L2T_LSTE.v002"],
    max_items=10000,
    limit=100,
    bbox=[ 2.35655221, 46.98119471,  2.37443578, 46.98873884],
    datetime=f"2023-01-01/2023-01-15",
)

s = c.search(**params)
_ = s.matched()

xs = s.item_collection()
xs[0].assets
```

**Comment by jaybarra** [comment]
The `view_zenith` object is available through STAC on the selected collections for each granule in that collection as an asset and not on the collection itself, but STAC doesn't have a way to map that as a defined download key. 

[ECO_L2T_LSTE.v002 granule in STAC](https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/ECO_L2T_LSTE.v002/items/ECOv002_L2T_LSTE_24418_001_11SKT_20221026T105945_0710_01) has a view_zenith tagged asset but only in the key. Its [corresponding umm_json](https://cmr.earthdata.nasa.gov/search/concepts/G2530780237-LPCLOUD.umm_json) defines it as a `GET DATA` type and no other information.
