### ISSUE TITLE
Version names with spaces are not correctly encoded.

### ISSUE THREAD

**Issue by jaybarra** [nasa/cmr-stac#333]
In the [CEOS_EXTRA](https://cmr.earthdata.nasa.gov/stac/CEOS_EXTRA/collections) collections page there are collections with spaces in the version name such as `USGS_SOFIA_eco_hist_db1995-2007.vversion 7` that should be URI encoded in the links.

**Comment by abbottry** [comment]
Additionally, "Not Provided" should not be a value included, seems like that should be translated to `null` or `undefined` depending on how its being used .

**Comment by eudoroolivares2016** [comment]
This should become OBE with the switch to entry_id field
[CMR-10122](https://bugs.earthdata.nasa.gov/browse/CMR-10122)
