### ISSUE TITLE
pagination failing

### ISSUE THREAD

**Issue by ircwaves** [nasa/cmr-stac#348]
cmr-stac pagination is failing. 

## Reproduction Scenario

Note this error is encountered with any collection, and is not specific to `HLS30_02.0`.

1. visit https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSL30_2.0/items

2. select the `next` link `.links[3].href` which will probably be something like this https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSL30_2.0/items?cursor=eyJqc29uIjoiW1wibHBjbG91ZFwiLDEzNjU2MzkzMzI4ODgsMjI0NzA2MTU3MF0iLCJ1bW0iOiJbXCJscGNsb3VkXCIsMTM2NTYzOTMzMjg4OCwyMjQ3MDYxNTcwXSJ9

3. get error  
```
"Oops! Something has gone wrong. We have been alerted and are working to resolve the problem. Please try your request again later."
```

**Comment by william-valencia** [comment]
A fix has been deployed to PROD, please retest and see if you are still experiencing this issue.

**Comment by ircwaves** [comment]
Bonked through the reproduction scenario, and it is working now.  1000x thank yous to you and the whole team!
