### ISSUE TITLE
HLS STAC "Oops!" error occurs daily at around 2 pm pacific time.

### ISSUE THREAD

**Issue by matus-hodul** [nasa/cmr-stac#366]
We noticed that the HLS “Oops!” error* seems to occur at roughly the same time every day, so we created a script which checks the status of HLS throughout the day. Indeed, the oops error occurs every day around 2 pm pacific time, and lasts for a couple hours, after which it resolves itself. There are other periods of oops error during the day as well, but these are shorter and don’t seem to follow a specific pattern.

<img width="1009" alt="Screenshot 2024-10-29 at 8 59 27 AM" src="https://github.com/user-attachments/assets/af26b69e-e35c-4687-a42b-854a85270848">

\* full error is: pystac_client.exceptions.APIError "Oops! Something has gone wrong. We have been alerted and are working to resolve the problem. Please try your request again later."

```python
import sys, os
from pystac_client import Client
import time

def checkHLS():
    try: # run a large HLS Query:
        url = r'https://cmr.earthdata.nasa.gov/stac/LPCLOUD'
        cat = Client.open(url)

        geom = {
                'type': 'Polygon',
                'coordinates': [[[-121.48363199406296, 50.58244919445883], # for an ROI near Cache Creek, BC.
                                [-121.44546042608697, 50.58244919445883], # normally these coords are derived from a .shp
                                [-121.44546042608697, 50.700797792110535], # but I didn't include that part in this demo.
                                [-121.48363199406296, 50.700797792110535],
                                [-121.48363199406296, 50.58244919445883]]]
        }

        params = {
            'intersects': geom,
            'collections': ['HLSL30.v2.0'],
            'datetime': '2018-01-01/2024-01-01'
        }

        search = cat.search(**params)
        items = search.item_collection()

        # If it works, return a status code of 1
        return 1, None, None
    
    except: # if it doesn't work, return a status code of 0 and the error message
        the_type, the_value, the_traceback = sys.exc_info() # https://stackoverflow.com/a/19406123

        return 0, the_type, the_value
```

**Comment by aliciaaleman** [comment]
Thanks for posting this issue in the repo. We're looking into it, but so far, it doesn't appear to be a CMR-STAC issue but rather something happening upstream with CMR.

**Comment by aliciaaleman** [comment]
Hi @waltersdan -  These issues appear to be caused by periodic bursts of user-driven activity (e.g., scripts harvesting a large amount of data). We're working alongside our operations and infrastructure teams to identify a solution. I'll post another update here when I have more information on a timeline for resolution.

**Comment by waltersdan** [comment]
Ok, thanks for the update!

**Comment by SethDocherty** [comment]
@aliciaaleman, I've had success with the `cloudstac` endpoint vs the `stac` endpoint (as noted [here](https://github.com/[nasa/cmr-stac](https://github.com/nasa/cmr-stac?tab=readme-ov-file#endpoints)?tab=readme-ov-file#endpoints)).

I understand that the `cloudstac` endpoint only contains STAC collections available in the cloud, but is there any reason I should be using `stac` instead to get **HLSS30.v2.0** metadata? I did a quick test comparing search results (similar to @matus-hodul search params) between both endpoints and didn't see a difference, so I assume using either endpoint is fine.

Other than the [update to the collection id](https://lpdaac.usgs.gov/news/important-update-to-cmr-stac-new-identifier-and-search-parameter-format/), the only difference I see is the API specs.
#### cloudstac endpoint
> **Conformance Classes**
OGC
OGC API - Features - Part 1 - Core 1.0
OGC API - Features - Part 1 - Oas30 1.0
OGC API - Features - Part 1 - Geojson 1.0
**STAC**
Core v1.0.0-beta.1
Item Search v1.0.0-beta.1
Item Search - Fields v1.0.0-beta.1
Item Search - Query v1.0.0-beta.1
Item Search - Sort v1.0.0-beta.1
Item Search - Context v1.0.0-beta.1

#### stac endpoint
> **Conformance Classes**
OGC
OGC API - Features - Part 1 - Core 1.0
OGC API - Features - Part 1 - Oas30 1.0
OGC API - Features - Part 1 - Geojson 1.0
OGC API - Common - Part 1 - Simple Query 1.0
**STAC**
Core v1.0.0-rc.2
Item Search v1.0.0-rc.2
Ogcapi Features v1.0.0-rc.2
Item Search - Fields v1.0.0-rc.2
Item Search - Features v1.0.0-rc.2
Item Search - Query v1.0.0-rc.2
Item Search - Sort v1.0.0-rc.2
Item Search - Context v1.0.0-rc.2
Collection Search v1.0.0-rc.2
Collection Search - Free Text v1.0.0-rc.2
Collection Search - Sort v1.0.0-rc.2

**Comment by william-valencia** [comment]
Are you all still getting the Oops error at 2pm pacific time?

**Comment by eudoroolivares2016** [comment]
@SethDocherty In the upcoming release noted in https://github.com/nasa/cmr-stac/releases/tag/CMRSTAC-r24.4.5 we'll be updating the `cloudstac` endpoint so that the version matches between both stac and `cloudstac`. The `cloudstac` endpoint will also support the additional conformance classes

**Comment by matus-hodul** [comment]
There appears to still be an error happening around 2 pm pacific time, lasting a couple hours each day. The error message now reads "CMR Search rate exceeded". Is there a search rate that we are individually limited to that we need to know about? Or is this a global search rate for everyone trying to query the data?

**Comment by eudoroolivares2016** [comment]
@matus-hodul  There was rate limit added to certain queries in `cmr-stac` specifically those made against `LPDAAC` provider searching over `HLSS` or `HLS` collections. This was done to prevent the API from throwing errors due to too many requests for the rest of the users of stac.
We are working to identify the agents making the excessive calls daily at 5pm ET and restrict their requests so that we can allow other users to browse the catalog without throttling

**Comment by waltersdan** [comment]
Could we re-open this issue until it is resolved? From a user point of view, the problem is still there, we just see a different error message.

**Comment by william-valencia** [comment]
Sure. The rules have been updated and the limit should not be individually limited. Please try it out and let us know if you are still experiencing issues.

**Comment by william-valencia** [comment]
So how are things running now for you all? @waltersdan @matus-hodul

**Comment by matus-hodul** [comment]
It seems that this latest update has fixed the issue, there has been no more down-time at 2 pm for the past couple days.

**Comment by waltersdan** [comment]
Yes all good, thanks for the help!

**Comment by scottstanie** [comment]
Sorry if this is the wrong place, but is this issue still coming up occasionally? I just happened to try to run https://github.com/ceos-org/cloud-native-geospatial-eo-workshop/blob/main/Cloud_Native_Land_Productivity_For_SDG15.ipynb for the first time, and the `stac_client.search` line is giving the "Oops!" error

**Comment by eudoroolivares2016** [comment]
@scottstanie I am able to reproduce the issue you see on that `jupyter` notebook though I haven't come up with a fix yet. In the latest release https://github.com/nasa/cmr-stac/releases/tag/CMRSTAC-r24.4.5 we took an action to migrate `cloud-stac` to a new version which included a change in the ids see [here](https://lpdaac.usgs.gov/news/important-update-to-cmr-stac-new-identifier-and-search-parameter-format/)

I did try updating the `jupyter` notebook to use `collections = ["HLSL30_2.0", "HLSS30_2.0"]` but, still seeing that error. This post isn't the exact same issue, the one this `github` issue is for was/is related to usage pattens from what seem to be automated scripts around 2pm Pacific. We will investigate where the problem is occurring in that `jupyter` notebook since the latest release of cloudstac

**Comment by eorland** [comment]
> Sure. The rules have been updated and the limit should now be individually limited at 60 requests/min. Please try it out and let us know if you are still experiencing issues.

@william-valencia Not sure about the likelihood of this, but would it be possible to have these adjusted on a case-by-case basis? I am an internal NASA user and have previously been able to work with HLS for prototyping potential operational workflows and scientific analyses. Thus far, it appears that this rate limit change has prohibited my querying of multi-year time series over even (relatively) small spatial domains (~114km2). I also tried implementing a `sleep` function into my workflow, but I'm still being thrown an error that the rate has been exceeded. Thank you!
