### ISSUE TITLE
Create an 'all' catalog for CMR STAC

### ISSUE THREAD

**Issue by doug-newman-nasa** [nasa/cmr-stac#368]
Currently, we have a catalog for each CMR provider. Since you can only conduct a collection search against a catalog we are lacking the ability to perform a collection search access all collections. This is problematic for two reasons:

1. Our federated search capabilities do not require the user to know which provider holds their data
2. If we want to re-architect our catalog system around STAC (See super STAC) we would need this capability.

Proposed solution:
Add a new catalog that encompasses all of our holdings.

Risks:

- Whatever we call it we need to make sure we don't give a new provider the same name

**Comment by aliciaaleman** [comment]
Closing this issue - The "all" CMR-STAC catalog feature was deployed to production 12/18/2024.
