### ISSUE TITLE
MODIS collection errors

### ISSUE THREAD

**Issue by JonDHo** [nasa/cmr-stac#371]
There seem to currently be various issues with STAC records, but I thought I would add this as another report as it doesn't relate to the HLS issues reported previously.

The `/items` endpoint for some MODIS collections fails completely and searches often fail. For example, the collection endpoint at https://cmr.earthdata.nasa.gov/stac/OB_DAAC/collections/MODISA_L2_OC_R2022.0 works, but https://cmr.earthdata.nasa.gov/stac/OB_DAAC/collections/MODISA_L2_OC_R2022.0/items returns the "Oops! Something has gone wrong." error. 

The same goes for other MODIS collections like:
- [MODISA_L2_IOP_R2022.0/items](https://cmr.earthdata.nasa.gov/stac/OB_DAAC/collections/MODISA_L2_IOP_R2022.0/items)
- [MODIST_L2_IOP_R2022.0/items](https://cmr.earthdata.nasa.gov/stac/OB_DAAC/collections/MODIST_L2_IOP_R2022.0/items)
- [MODIST_L2_OC_R2022.0/items](https://cmr.earthdata.nasa.gov/stac/OB_DAAC/collections/MODIST_L2_OC_R2022.0/items)

but the SST collections work: 
- [MODIST_L2_SST_R2019.0/items](https://cmr.earthdata.nasa.gov/stac/OB_DAAC/collections/MODIST_L2_SST_R2019.0/items)
- [MODISA_L2_SST_R2019.0/items](https://cmr.earthdata.nasa.gov/stac/OB_DAAC/collections/MODISA_L2_SST_R2019.0/items)

I frequently get the "Oops!" error when searching using PySTAC and PySTAC Client as well (which should be using POST requests).

**Comment by aliciaaleman** [comment]
@JonDHo We have a fix working through our test environment that may resolve some of these issues but we'll confirm before closing this out.

**Comment by eudoroolivares2016** [comment]
This should now be fixed in production. For those wondering it was an issue with a type in an upstream dependency that cmr-stac has
