### ISSUE TITLE
hierarchical links have double slash

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cmr-stac#5]
The dynamically generated hierarchical links have an extra slash between the root and the relative endpoint.  See the self and parent links in any Item as an example:

https://pcmii5dog3.execute-api.us-east-1.amazonaws.com/dev//collections/C204582034-LPDAAC_ECS/items/G205234693-LPDAAC_ECS

**Comment by matthewhanson** [comment]
This is not the case when using the domain: https://cmr-stac-api.dev.element84.com/collections

Still, the trailing slash from root, if present, should be removed before appending.

**Comment by RincioneCMR** [comment]
Verified.
