### ISSUE TITLE
datetime field is incorrect

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cmr-stac#6]
The `datetime` property in a STAC Item is a single datetime, but the datetime field in cmr-stac is two datetimes separated by a slash. 

The `datetime-range` extension should be used to represent the start_datetime and end_datetime fields: https://github.com/radiantearth/stac-spec/tree/master/extensions/datetime-range

Note that in the upcoming STAC 0.9.0 the datetime-range extension will change to not use a prefix in the field names (i.e., `start_datetime` rather than `dtr:start_datetime`)

**Comment by matthewhanson** [comment]
Populate these 3 properties:

- datetime
- start_datetime
- end_datetime

**Comment by RincioneCMR** [comment]
Verified.
