### ISSUE TITLE
temporal extent in most Collections incorrect

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cmr-stac#7]
Some of the temporal extents given appear to be incorrect.

For instance the LANCE MODIS L2 swath data: https://pcmii5dog3.execute-api.us-east-1.amazonaws.com/dev//collections/C1426717545-LANCEMODIS
has 2017-10-20T00:00:00.000Z as both the start and end temporal extent, which is clearly wrong.

And the non NRT version also has a single date for the start and end extent:
https://pcmii5dog3.execute-api.us-east-1.amazonaws.com/dev//collections/C1443528505-LAADS

For ICESat-2 ATL06 we also see the same thing, where there is a single date for start and end:
https://pcmii5dog3.execute-api.us-east-1.amazonaws.com/dev//collections/C1631076765-NSIDC_ECS

It appears that nearly all the Collections are incorrect, although the NCEP Reanslysis: https://pcmii5dog3.execute-api.us-east-1.amazonaws.com/dev//collections/C1237113465-GES_DISC
appears to have reasonable values for the temporal extent.

**Comment by RincioneCMR** [comment]
End time for an ongoing collection is now "null."

**Comment by tvance34** [comment]
To be more specific on this issue, there are two problems that were seen:

1.) on-going collections need a null end date
2.) start and end dates should not be the same

**Comment by RincioneCMR** [comment]
Verified.
