### ISSUE TITLE
Incorrect item asset "types"

### ISSUE THREAD

**Issue by scottyhq** [nasa/cmr-stac#91]
First of all, thanks for putting this together! I think it is going to be an amazing resource for consistent, programmatic access to NASA data.

After a bit of initial testing I've noticed some incorrect assignment of asset type (which complicates opening remote assets):

https://cmr.earthdata.nasa.gov/cmr-stac/NSIDC_ECS/collections/C1908075185-NSIDC_ECS/items/G1921160949-NSIDC_ECS 
```
  "assets": {
    "0": {
      "href": "https://n5eil01u.ecs.nsidc.org/DP4/MEASURES/NSIDC-0723.003/2015.01.01/GL_S1bks_mosaic_01Jan15_12Jan15_shape_v03.0.shx",
      "type": "application/x-geotiff"
    },
```

https://cmr.earthdata.nasa.gov/cmr-stac/NSIDC_ECS/collections/C1908075185-NSIDC_ECS/items/G1923750834-NSIDC_ECS
```
  "assets": {
    "data": {
      "href": "https://n5eil01u.ecs.nsidc.org/DP4/MEASURES/NSIDC-0723.003/2015.01.01/greenland_v03.0.mov",
      "type": "application/x-geotiff"
    },
```

I'm guessing `"type": "application/x-geotiff"` is set as default somewhere if the filetype doesn't exist or isn't recognized in the original CMR metadata?

**Comment by matthewhanson** [comment]
@scottyhq It turns out that the mime type comes from the source provider metadata, so it's out of the control of cmr-stac.

Have you found mis-identified assets in collections other than this one?

**Comment by william-valencia** [comment]
Closing this issue as it looks to be a mismatch at the source provider metadata.
